### ISSUE TITLE
[TS] Cannot find module @octokit/core.

### ISSUE THREAD

**Issue by sustained** [octokit/plugin-throttling.js#127]
```
node_modules/@octokit/plugin-throttling/dist-types/index.d.ts:1:25 - 
  error TS2307: Cannot find module '@octokit/core'.

1 import { Octokit } from "@octokit/core";
                          ~~~~~~~~~~~~~~~
```

I'm using [module-alias](https://www.npmjs.com/package/module-alias), [ESM](https://www.npmjs.com/package/esm) and lately also TypeScript and it hasn't really caused issues with anything else as of yet.

Here's my `GithubClient.ts`:

```ts
import * as Octokit from '@octokit/rest'
import OctokitPluginThrottling from '@octokit/plugin-throttling'

import { NAME, VERSION } from '@libraries/constants'

const { GITHUB_TOKEN } = process.env

Octokit.plugin((OctokitPluginThrottling as unknown) as Octokit.Plugin)

const client = new Octokit({
  auth: GITHUB_TOKEN,
  userAgent: `${NAME} [${VERSION}] (octokit/rest)`,
  throttle: {
    onRateLimit: (retryAfter: number, options) => {
      client.log.warn(
        `[GithubClient] Request quota exhausted for request ${options.method} ${options.url}`
      )

      console.log(`Retrying after ${retryAfter} seconds!`)
      return true
    },
    onAbuseLimit: (_retryAfter: number, options) => {
      client.log.warn(
        `[GithubClient] Abuse detected for request ${options.method} ${options.url}`
      )
    },
  },
})

export default client
```

Any ideas? I can provide more info. if necessary.

Also, as you can see, I was forced to do this -

```ts
Octokit.plugin((OctokitPluginThrottling as unknown) as Octokit.Plugin)
```

And to import Octokit in a strange was `* as` too.

None of the other libraries/frameworks I'm using have this issue.

Thank you!

**Comment by gr2m** [comment]
Which version of `@octokit/plugin-throttling` do you have installed? You can check with `npm ls @octokit/plugin-throttling`. Note that we recently released a new breaking version that you need to import like this:

```js
import { throttling } from '@octokit/plugin-throttling'
```

You might need to install `@octokit/core` as a development dependency, this is only temporary until `@octokit/rest` v17 is released: https://github.com/octokit/rest.js/issues/1546

Alternatively, you can use `@octokit/core` instead of `@octokit/rest`, it will work better with TypeScript as there should be no discrepancy. `@octokit/core` itself is written in TypeScript.

If you want the methods for every REST API endpoints, load this plugin: https://github.com/octokit/plugin-rest-endpoint-methods.js. Other plugins that you might want are

- https://github.com/octokit/plugin-paginate-rest.js
- https://github.com/octokit/plugin-request-log.js

**Comment by sustained** [comment]
Yeah, it was just that I needed to install it myself (was just unexpected) - thank you!

**Comment by gr2m** [comment]
Hey unrelated question, what is the `@libraries/constants` doing in your code? I'm curious
