### ISSUE TITLE
Error: This job timed out after 60000 ms.

### ISSUE THREAD

**Issue by gr2m** [octokit/plugin-throttling.js#23]
I found two of these errors in WIP, in quick succession, on the same node (WIP is running on 2-4)

```
Error: This job timed out after 60000 ms.
    at Timeout._scheduled.(anonymous function).expiration.next.options.expiration.setTimeout (/home/nowuser/src/node_modules/bottleneck/lib/Bottleneck.js:262:28)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

Any idea what it could mean?

**Comment by gr2m** [comment]
Looks like it’s caused by a memory leak, which causes the event handler process duration to grow exponentially right before server gets restarted:

Top: memory usage in bytes
Bottom: duration in ms

![image](https://user-images.githubusercontent.com/39992/51848839-3b4f3000-22d3-11e9-86f5-7e6d4e302889.png)

**Comment by SGrondin** [comment]
It's not caused by a memory leak, it's because a job took longer than 1 minute to run. 1 minute is what I've set the job TTL to, we can make it longer if we want. We need a TTL because servers can crash/restart/etc and those orphaned jobs (GH requests) would be taking up throttling resources forever.

The Clustering memory usage is a different issue and should be similar to the usage without Cluster once we merge PR #22

**Comment by gr2m** [comment]
What I meant to say is that the duration of handling requests peaks right before the server crashes and restarts, that was the case even before introducing the new throttling. So I don’t think that the timeout is a problem, I expect that once we fix the memory issue, this problem will go away
