### ISSUE TITLE
LimitHandler typing uses type `object` for options

### ISSUE THREAD

**Issue by Thodor12** [octokit/plugin-throttling.js#641]
Relevant line: https://github.com/octokit/plugin-throttling.js/blob/main/src/types.ts#L6

The `object` type is not readable, even though the examples show doing things like "options.method" or "options.url", but with Typescript, none of this works:

![2023-11-02 19_02_38-Window](https://github.com/octokit/plugin-throttling.js/assets/14359461/855f8afa-d64b-40bc-8420-058e8167fd51)

tsconfig.json:
```json
{
  "compilerOptions": {
    "strict": true,
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "allowSyntheticDefaultImports": true,
    "noErrorTruncation": true
  }
}
```

And relevant package versions:
```
    "@octokit/auth-token": "^4.0.0",
    "@octokit/plugin-throttling": "^8.1.2",
    "@octokit/rest": "^20.0.2",
```

**Comment by CatChen** [comment]
I haven't upgraded this dependency since `5.2.0` because of this. The `options` is still constructed from [a known structure](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L105) and it even adds `retryCount` for [backward compatibility](https://github.com/octokit/plugin-throttling.js/blob/main/src/index.ts#L118), but it's no longer typed.

**Comment by wolfy1339** [comment]
Thank you for bringing this up to our attention. I have created a PR to fix this problem and add proper types for the `options` parameter 

Feel free to look it over and leave a review
#642
